# Generated by Django 4.2.6 on 2023-10-27 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_post_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='created_at',
        ),
    ]
